### ISSUE TITLE
Error when injecting the icon provider

### ISSUE THREAD

**Issue by baumgarb** [angular/material-start#100]
Hi,

hope I'm not wrong with that but as far as I can see there's an error in the tutorial when injecting the icon provider. Referring to the branch es5-tutorial the error occurs in the tutorial step number 4. The code according to the tutorial is something like that:
 
```js
angular
    .module('starterApp', ['ngMaterial', 'users'])
    .config(function( $mdIconProvider ){

        // Register the user avatar icons
        $mdIconProvider
                .defaultIconSet("./assets/svg/avatars.svg", 128);
    });
```

Executing this code angular raises an error saying: _Unknown provider: $mdIconProviderProvider_

If I change the parameter from $mdIconProvider to _$mdIcon_ angular resolves the provider properly, but then angular gives me a _TypeError_ telling me, that _$mdIcon.defaultIconSet_ is not a function.

I'm somehow lost with that...

**Comment by ThomasBurleson** [comment]
Consider this JsBin http://jsbin.com/manewahome/edit?html,output

![screen shot 2016-03-01 at 8 45 52 am](https://cloud.githubusercontent.com/assets/210413/13430281/09cec80e-df8a-11e5-8376-dae60725e027.png)

If you look at the dev console, you will not see any errors AND the avatars render as desired.

> That JSBin uses the `angular/bower-material/master` branch and Angular 1.4.9.

**Comment by ThomasBurleson** [comment]
I am unclear why you are getting such an error. Please provide a codePen or JSbin to validate and resolve your error.

**Comment by baumgarb** [comment]
First of all thanks a lot for replying that fast! I uploaded the sample as it is [here](http://www.baumgarb.at/ngMaterial/mdIconProviderSample/)

Even though it's not CodePen oder JSBin but you should be able to reproduce the issue if you open up any browser's developer tools and take a look at the console. All libraries were installed using bower yesterday.

Thanks a lot in advance for spending your time on my issue!

**Comment by ThomasBurleson** [comment]
You are trying to configure the provider in the `.run( ... )` block:

```js
angular
    .module("mdIconProviderApp", ["ngMaterial"])
    .run(function ($mdIconProvider) {
        // Register the user `avatar` icons
        // $mdIconProvider.defaultIconSet("./assets/svg/avatars.svg", 128);
        // $mdIcon.icon("menu", "./assets/svg/menu.svg", 24);
    });
```

Try using the `.config( ... )` block:

```js
angular
    .module("mdIconProviderApp", ["ngMaterial"])
    .config(function ($mdIconProvider) {
        // Register the user `avatar` icons
        // $mdIconProvider.defaultIconSet("./assets/svg/avatars.svg", 128);
        // $mdIcon.icon("menu", "./assets/svg/menu.svg", 24);
    });
```

**Comment by baumgarb** [comment]
Oh man *facepalm* I am really sorry for bothering you, yes you're right, that was the problem.

Thank you very much!
