### ISSUE TITLE
Wrong contact is highlighted after clicking

### ISSUE THREAD

**Issue by sasrar** [angular/material-start#105]
After clicking on a contact and then clicking on a different contact the previously selected contact is highlighted gray. 

![image](https://cloud.githubusercontent.com/assets/2454882/13784927/3868e8f0-ea9f-11e5-88fc-5f069b5179c8.png)

**Comment by Para96** [comment]
I'm experiencing this problem aswell, any news on this?

**Comment by DoubleAix** [comment]
html:
`<md-sidenav md-is-locked-open="$mdMedia('gt-sm')" md-component-id="left" **ng-click="ul.toggleList()"**>`
`<md-sidenav md-is-locked-open="$mdMedia('gt-sm')" md-component-id="left" **ng-click="ul.closeList()"**>`
js:
```
self.closeList = closeUsersList;
function closeUsersList() {
    $mdSidenav('left').close();
}
```
i am just a  beginner of Javascirpt
i don't know why this change can solve this issue, anyone know why?

**Comment by ThomasBurleson** [comment]
Not an issue on the `es6` and `es6-tutorial` branches.
