### ISSUE TITLE
Document running live-serer better

### ISSUE THREAD

**Issue by drorm** [angular/material-start#113]
Please make explicit that you  run live-server in the root dir, but go to hostname:8080/app. The paths are wrong if you to run liveserver in the app dir.

Also, no need to install live-server -g. You can just do 
./node_modules/.bin/live-server

**Comment by topherfangio** [comment]
We've updated the tutorial to use `live-server --open=app` as well as adding some additional docs to account for this issue.

Thanks for pointing it out!
