### ISSUE TITLE
npm install fails because angular-material version is invalid

### ISSUE THREAD

**Issue by trippdaddy** [angular/material-start#131]
In the current package,json file, the release for angular-material is a GitHub URL. That causes rpm install to fail. I changed it to the following and all is good again.

  "dependencies": {
    "angular": "^1.5.5",
    "angular-animate": "^1.5.5",
    "angular-aria": "^1.5.5",
    "angular-messages": "^1.5.5",
    "angular-material": "^1.0.8"
  },

**Comment by ThomasBurleson** [comment]
Fixed with SHA 15abbf8089cba21b7e773f97810cf8d68e9eb2c5
