### ISSUE TITLE
npm can't find script "tests"

### ISSUE THREAD

**Issue by tarasrng** [angular/material-start#133]
When I'm running npm run tests I see the error in console:

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\DevSoft\\NodeJs\\node.exe" "C:\\Users\\Taras\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "tests"
npm ERR! node v5.7.1
npm ERR! npm  v3.8.9

npm ERR! missing script: tests
```
I've checked package.json - there is no "tests" script. What do I do wrong?

**Comment by gnerkus** [comment]
I believe the tests have been disabled:

https://github.com/angular/material-start/commit/3a525fe89581c5b945388c1714ca3e4b64027d1e
