### ISSUE TITLE
Cannot run the material-start project

### ISSUE THREAD

**Issue by LouisJS** [angular/material-start#135]
Npm install loop on :

fetchMetadata → resolveWi ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

I cannot go further in the process.
Is there something to fix first in package.json ?

**Comment by ThomasBurleson** [comment]
@LouisJS - please provide more information:

* which branch are you using on `material-start` ?
* which version of Node, NPM, and gulp ?

**Comment by LouisJS** [comment]
@ThomasBurleson 

 I'm using the basic branche (Master)
Version :

- Npm  :  3.8.3
- Node : v5.10.0

I don't have gulp.

**Comment by ThomasBurleson** [comment]
```console
cd <project_root>;
npm update; npm install -g live-server
live-server;
```

Browse to `http://127.0.0.1:8080/app/`.

> This works fine in `master`.
