### ISSUE TITLE
ES5 Step #4 instructions - missing ng-controller and wrong file names

### ISSUE THREAD

**Issue by KarolinaCoates** [angular/material-start#147]
#1 Step 4 instructions don't mention that a **ng-controller** directive needs to be added to **<body>** tag:
`<body ng-app="starterApp" layout="column" ng-controller="UserController as ul">`

#2 Step 4 instructions say to add the following external .JS files:
`         <script src="./src/users/Users.js"></script>
         <script src="./src/users/UsersListController.js"></script>
         <script src="./src/users/UsersDataservice.js"></script>`

but the file names don't match, it should say this instead:
`     <script src="./src/users/Users.js"></script>
     <script src="./src/users/UserController_4.js"></script>
     <script src="./src/users/UserService.js"></script>`

**Comment by ThomasBurleson** [comment]
@KarolinaCoates - can you confirm the branch you were using ?

**Comment by KarolinaCoates** [comment]
@ThomasBurleson es5-tutorial

**Comment by topherfangio** [comment]
Closed via 1448a6380f5d34ebc0a175530e8f1ffadcd9e2da.
