### ISSUE TITLE
Update master with es6 tutorial and better notes.

### ISSUE THREAD

**Issue by topherfangio** [angular/material-start#149]
We would like to encourage users to use ES6 while building Material Start, but would also like to clarify the other branches and their purpose.

To do this, we will:

- [x] Ensure es5 and es5-tutorial branches are in-sync and up-to-date
- [x] Update the `master` branch to use the ES6 final code
- [x] Update the `master` README to include more information and links to the other branches

**Comment by ThomasBurleson** [comment]
Will use these branches at Angular Connect 2016.

**Comment by topherfangio** [comment]
Done; just need to make master the default branch.
