### ISSUE TITLE
Developing without npm or bower

### ISSUE THREAD

**Issue by nabinkhadka** [angular/material-start#159]
I just want to follow the tutorials without using npm or bower. I want to go this way because I want to create a profile web page in github.io where I cannot use a live-server. Just plain html, css with javascript. Can you please suggest?

**Comment by bethrobson** [comment]
Yes, I too would be very interested in understanding how to use this library without node, npm, bower, etc.  Can we just link to the relevant libraries or download them the old fashioned way (since these are client side tools)?

**Comment by bethrobson** [comment]
At the bottom of the tutorial, you write "With only ten (10) Tutorial Steps and a few minutes of work, we have quickly created a functional Angular Material application that is beautiful, responsive, theme'ed, accessible, component-based, and easily maintained." 

However, this assumes the reader/learner already understands how to use git, Node, npm, etc, as well as understands the directory structure required, where libraries are, how to configure for node, what bower is and how it fits in, etc. 

A tutorial that explains Angular Material without the use of all these other technologies would be very helpful.

**Comment by ThomasBurleson** [comment]
@bethrobson - If you are building web applications with Angular, you really must be familiar with Git and NPM. There is, however, merit in showing a CDN-based usage of Angular Material to run this material-start application using only an http server.

**Comment by bethrobson** [comment]
I'm trying to find an easy way to teach Angular and Angular Material with minimal burden to those new to JavaScript programming. The learning curve is incredibly steep because of all these other tools. 

Thanks for your input.

**Comment by RathofCon** [comment]
I was able to fully create step-4 over on Plnkr.co using code from GitHub user werzizu.  This is not a real server based app but it will demonstrate all of the aspects of Angular Material Starter tutorial.  It uses CDNs.
My Plnkr id is RathofCon

**Comment by EladBezalel** [comment]
I'd go with @ThomasBurleson answer, CDN is probably your best option - please check any of our codepen at https://material.angularjs.org.
