### ISSUE TITLE
not working. help

### ISSUE THREAD

**Issue by siyuandong** [angular/material-start#162]
after go through 4 steps I got the 127.0.0.1:8080/app working. then git status: modified:   app/config.js.
I commit the changes, checkout step-1, or step-6, or step-10.. either of them shows anything. 

checkout es6-tutorial again then shows the list. 

console show Timestamp: 12.12.2016 21:41:35
Error: Content Security Policy: The page's settings blocked the loading of a resource at about:blank ("base-uri https://github.com").

**Comment by siyuandong** [comment]
checkout es6 got this
Timestamp: 12.12.2016 21:53:57
Error: The connection to ws://127.0.0.1:8080/app//ws was interrupted while the page was loading.
Source File: http://127.0.0.1:8080/app/
Line: 79

**Comment by Splaktar** [comment]
The `es6` branch has been fixed. step-1 was also fixed. If you are seeing issues with other steps, please open a new issue.
