### ISSUE TITLE
seamless integration of material design styles with offical angular-seed project

### ISSUE THREAD

**Issue by NilsHolger** [angular/material-start#166]
as a new user i want to use something new to style my angular 1 applications. i want to be able to seamlessly install angular-material 1.1.3 in the angular-seed project 1.6.1. please provide instructions in both readme's how to do this. if we wish the new users to adopt material design this is an essential step IMHO.

**Comment by ThomasBurleson** [comment]
@elad - can you work on this? Thx

**Comment by elad** [comment]
@ThomasBurleson I think you got the wrong person

**Comment by EladBezalel** [comment]
he probably did 😅 
Not sure this effort is essential, there are plenty of resources how to get started with material and i'm sure angular-seed is no different than any other example out there..

**Comment by ThomasBurleson** [comment]
@EladBezalel - can you test the angular-seed + angular-material combination to see if there are any issues. If needed, we can simply add a readme section with any special issues or steps.

**Comment by NilsHolger** [comment]
@ThomasBurleson cloned angular seed, i want to style my app quickly, bower install angular material get the same message: Unable to find a suitable version for angular, please choose one by typing one of the numbers below:
    1) angular#~1.5.0 which resolved to 1.5.11 and is required by ng1-githubcontributors
    2) angular#^1.4.8 which resolved to 1.5.11 and is required by angular-material#1.1.3
    3) angular#1.5.11 which resolved to 1.5.11 and is required by angular-route#1.5.11
    4) angular#1.6.2 which resolved to 1.6.2 and is required by angular-animate#1.6.2, angular-aria#1.6.2, angular-messages#1.6.2

Prefix the choice with ! to persist it to bower.json

this will turn off new users!
