### ISSUE TITLE
where are the tags?

### ISSUE THREAD

**Issue by dave-mitchell** [angular/material-start#168]
I've cloned the repository, but when I try to switch to a tag, I'm told there are no tags.  "git tag -l" produces no tags, even though I can see them on the github page, clearly listed as steps 1 - 10.  I feel like I'm not getting something very basic, here.

**Comment by ThomasBurleson** [comment]
`git fetch --all --tags`

**Comment by dave-mitchell** [comment]
Works.  I can't believe I didn't come across this in trying to figure out how to access tags.  Thanks so much for taking the time to explain!
