### ISSUE TITLE
Application is completely blank

### ISSUE THREAD

**Issue by otcdoc** [angular/material-start#169]
I went through the installation instructions but steps 1 - 10 all pull up a blank application.  Everything seems to be set to display:none or background-color transparent, so I'm not sure what I'm supposed to see at all (nothing seems to respond in any step either).

**Comment by ThomasBurleson** [comment]
@EladBezalel - can you investigate please.

**Comment by EladBezalel** [comment]
@otcdoc what tutorial brach did you follow ?

**Comment by otcdoc** [comment]
I attempted to follow the master branch.

**Comment by EladBezalel** [comment]
Please follow the es6 tutorial.

**Comment by jaibatrik** [comment]
Having the same issue, getting the following log in lite-server console - 

    GET /service-worker.js 404 0.374 ms - 30

**Comment by ThomasBurleson** [comment]
Fixed. Please use 

```console
git pull --rebase origin master;
npm i
cd app; live-server
```
