### ISSUE TITLE
Starting the application with "npm run serve" not working.

### ISSUE THREAD

**Issue by danielhansson** [angular/material-start#173]
Cloned a fresh copy and tried to start the application with "npm run serve" but it didn't work.

The command serve was removed in this commit:
https://github.com/angular/material-start/commit/7792fa091bffff90f52389abf031c77cb214aaac

See:
"serve": "live-server ./app"

**Comment by EladBezalel** [comment]
would be fixed with #172

**Comment by torzuoliH** [comment]
On the last version, `811cb12`, you can use `npm run-script serve`

**Comment by karthikgurumurthy** [comment]
TorzuoliH... that fixed my issue. Thank you so much!

**Comment by TorzuoliH** [comment]
You're welcome! 😸
