### ISSUE TITLE
typescript: typings ERR! message Attempted to compile "angular-animate" as a global module, but it looks like an external module

### ISSUE THREAD

**Issue by mzhua** [angular/material-start#174]
when exec "npm install" , it shows the error.
Here is the detail log

verbose lifecycle material-start@1.0.0~postinstall: CWD: /Users/hua/WebProjects/material-start
67 silly lifecycle material-start@1.0.0~postinstall: Args: [ '-c',
67 silly lifecycle   'typings install dt~jquery dt~angular dt~angular-animate dt~angular-material --global --save' ]
68 silly lifecycle material-start@1.0.0~postinstall: Returned: code: 1  signal: null
69 info lifecycle material-start@1.0.0~postinstall: Failed to exec postinstall script
70 verbose stack Error: material-start@1.0.0 postinstall: `typings install dt~jquery dt~angular dt~angular-animate dt~angular-material --global --save`
70 verbose stack Exit status 1
70 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
70 verbose stack     at emitTwo (events.js:106:13)
70 verbose stack     at EventEmitter.emit (events.js:194:7)
70 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
70 verbose stack     at emitTwo (events.js:106:13)
70 verbose stack     at ChildProcess.emit (events.js:194:7)
70 verbose stack     at maybeClose (internal/child_process.js:899:16)
70 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
71 verbose pkgid material-start@1.0.0
72 verbose cwd /Users/hua/WebProjects/material-start
73 error Darwin 16.5.0
74 error argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "install"
75 error node v7.9.0
76 error npm  v4.2.0
77 error code ELIFECYCLE
78 error errno 1
79 error material-start@1.0.0 postinstall: `typings install dt~jquery dt~angular dt~angular-animate dt~angular-material --global --save`
79 error Exit status 1
80 error Failed at the material-start@1.0.0 postinstall script 'typings install dt~jquery dt~angular dt~angular-animate dt~angular-material --global --save'.
80 error Make sure you have the latest version of node.js and npm installed.
80 error If you do, this is most likely a problem with the material-start package,
80 error not with npm itself.
80 error Tell the author that this fails on your system:
80 error     typings install dt~jquery dt~angular dt~angular-animate dt~angular-material --global --save
80 error You can get information on how to open an issue for this project with:
80 error     npm bugs material-start
80 error Or if that isn't available, you can get their info via:
80 error     npm owner ls material-start
80 error There is likely additional logging output above.
81 verbose exit [ 1, true ]

**Comment by Reloecc** [comment]
@mzhua did you resolved this and how? I just started with AngularJS, attempted to install Material from this repo, and ended with same result after 30 seconds - quick experience xD.

**Comment by mzhua** [comment]
@Reloecc sorry, i still don't know how to fix this, and i realize this is for 1.x . And now, i use mateiral2 and it works fine [material2](https://github.com/angular/material2)

**Comment by mcrisp** [comment]
change the scripts declaration in the package.json file to remove the --global tag and also remove jquery from the list.  

the scripts declaration should look like this now...

 "scripts": {
    "postinstall": "typings install  dt~angular dt~angular-animate dt~angular-material --save"
  }

**Comment by Splaktar** [comment]
Fixed in https://github.com/angular/material-start/commit/bbd3f569925283d186b9dac9f2612e8339e70728.
