### ISSUE TITLE
how to add ui-router for es6 version?

### ISSUE THREAD

**Issue by bochuxt** [angular/material-start#180]
Hello, I would like to use ui-router for es6, anyone can help me?

**Comment by bochuxt** [comment]
"angular-ui-router": "npm:angular-ui-router@0.4.2",
"angular-ui-grid": "npm:angular-ui-grid@^4.0.6",


  .controller('AppController', AppController)
    // .controller('HomeController', HomeController)
    .config(function ($stateProvider, $urlRouterProvider) {





        $stateProvider
            .state('users', {
                url: '/users',
                templateUrl: './src/users/usersView.html',
                // controller: 'AppController',
                // controllerAs: 'app'
            });

        $stateProvider
            .state('home', {
                url: '/home',
                templateUrl: './src/corp/home.html',

            });
        $stateProvider
            .state('profile', {
                url: '/profile',
                templateUrl: './src/profile/profile.html',
                controller:'ProfileCtrl',
                controllerAs: 'profileCtl',
                params: {
                    // srouce: "login",// from purchase or login
                    totalAmount:"",
                    cart:'',        //from purchase
                    products:'',     //from login
                    user:''

                },

            });

**Comment by Splaktar** [comment]
You don't mention what issue you were running into. Have you tried looking at the [ui-router Tutorial](https://ui-router.github.io/ng1/tutorial/helloworld)?
