### ISSUE TITLE
Unhandled rejection

### ISSUE THREAD

**Issue by allentc** [angular/material-start#188]
When $mdBottomSheet in app/src/users/components/details/UserDetails.js is dismissed without selecting one of the items Chrome will log a "Possibly unhandled rejection: undefined" error with AngularJS 1.6.x.  The solution is to add:

    .catch(angular.noop);

on the end of the callback chain.

**Comment by Splaktar** [comment]
Was this on master or one of the branches?

**Comment by allentc** [comment]
I imagine I pulled master at the time.  I just tried to reproduce this with the master tree (7525f1622d52a938eaf51c5a10953ea9047e031b )I have and did not see the unhandled rejection report in Chrome.  Sorry I can't provide precise information.

**Comment by Splaktar** [comment]
OK, great, thank you for the quick response! I think that this has been resolved.

**Comment by Splaktar** [comment]
It looks like this might have been in the `typescript` branch. Fixed there in https://github.com/angular/material-start/commit/7753d5a8e995a26403dd0ce6e9487ac79a931e49.
