### ISSUE TITLE
document app.css

### ISSUE THREAD

**Issue by lookfirst** [angular/material-start#19]
https://github.com/angular/material-start/blob/master/app/assets/app.css

Where did this file come from?
How does it apply to material design?
Why does it seem to be so responsible for the look and feel?
Why isn't it scss?

I guess my confusion is more around why this isn't just part of angular/bower-material/angular-material.css? It doesn't feel very re-usable and feels kind of hidden in this starter project.

**Comment by marcysutton** [comment]
I think there are quite a few styles in there that can be removed once https://github.com/angular/material/pull/1985 is merged. But I think the general idea is that you should have a file with your specific overrides in it. If there are that many look-and-feel styles in app.css even when angular-material.css is included, it points out holes in our CSS API.

**Comment by lookfirst** [comment]
Just commenting out the app.css, it feels like there is quite a bit of style being declared that is helpful at a framework level.

http://take.ms/b9oDT vs. http://take.ms/X7Ivw
