### ISSUE TITLE
Can not execute 'bower update' 

### ISSUE THREAD

**Issue by palacios335** [angular/material-start#23]
I'm trying to get the material start, the cloning of the repository has been done successful, but when I type 'bower update' I get the follow error:

50212 info install material-start@0.0.0
50213 info postinstall material-start@0.0.0
50214 verbose unsafe-perm in lifecycle true
50215 info material-start@0.0.0 Failed to exec postinstall script
50216 error material-start@0.0.0 postinstall: `bower update`
50216 error Exit status 1
50217 error Failed at the material-start@0.0.0 postinstall script.
50217 error This is most likely a problem with the material-start package,
50217 error not with npm itself.
50217 error Tell the author that this fails on your system:
50217 error     bower update
50217 error You can get their info via:
50217 error     npm owner ls material-start
50217 error There is likely additional logging output above.
50218 error System Windows_NT 6.2.9200
50219 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
50220 error cwd C:\Users\EnriqueJose\Desktop\material-start
50221 error node -v v0.10.32
50222 error npm -v 1.4.28
50223 error code ELIFECYCLE
50224 verbose exit [ 1, true ]

**Comment by mrblueblue** [comment]
I think the appropriate command is ```bower install```

This will install all the package dependencies in the ```bower.json``` file to app/bower_components.

**Comment by palacios335** [comment]
After running the npm install, behind the scenes of this command "bower install" will run but I get the error, and bower_components directory is not created

**Comment by ThomasBurleson** [comment]
@palacios335  - you are able to use `bower install` or `bower update` within other projects on your WinNT machine ?

**Comment by palacios335** [comment]
I can't. I get this
![captura](https://cloud.githubusercontent.com/assets/9358097/6879544/118653c2-d4bf-11e4-9a33-6958321f7f4c.JPG)

**Comment by mprentic-harris** [comment]
Are you on a corporate machine and corporate network? Proxies often cause issues with bower and npm. @palacios335 Is this still an issue for you?

**Comment by palacios335** [comment]
@mprentic-harris yes it 's a corporate network

**Comment by palacios335** [comment]
Thanks. It was the proxy configuration

2016-01-29 13:55 GMT-06:00 Thomas Burleson <notifications@github.com>:
