### ISSUE TITLE
Question about <md-select> 

### ISSUE THREAD

**Issue by rishighan** [angular/material-start#25]
I was reading through the principles of Material Design; specifically, `Menus` -  http://www.google.com/design/spec/components/menus.html#

How closely is Angular-material trying to follow the principles laid down my Material Design? 
The docs page about menus clearly shows an example for the mobile layout. I am assuming the same does not apply to a desktop when it comes to dropdowns. 

To that end, where does the look for `md-select` come from? What is the motivation for the single pixel bottom border? 

The way a dropdown normally acts will reflect the user selection once it has been made. This is in contrast with the "quick action menu" in Material Design, which is represented by the three vertical dots and does not reflect user selection.

**Comment by marcysutton** [comment]
@rishighan you should ask that question in the [ngMaterial forum](https://groups.google.com/forum/#!forum/ngmaterial)....or if it is actually a feature request or bug report, the [Angular Material Github](https://github.com/angular/material) repository. It's outside of the scope of Material Start.
