### ISSUE TITLE
Bottomsheet interferes with SideNav 

### ISSUE THREAD

**Issue by ThomasBurleson** [angular/material-start#3]
Scrolling with bottomSheet shows sideNav is not full height.

**Comment by marcysutton** [comment]
@ThomasBurleson I actually think we should either remove Bottom Sheet or transform it into another component on desktop since it is supposed to be mobile-only.

**Comment by marcysutton** [comment]
Fixed with 08916161a40565e6ee0b1a6a3a12c5b3b599cbbd.
