### ISSUE TITLE
Can't install webdriver-manager update on windows

### ISSUE THREAD

**Issue by aminx4** [angular/material-start#38]
Hello Everybody, 

I'm trying to use the tutorial in https://github.com/angular/material-start for getting my first angular material design app, but i have a problem in this step : 

D:\Formations\Angular Material Design\Repository\material-start>webdriver-manager update
'webdriver-manager' n'est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

can anyone help me to resolve this.

thank you for your help.

**Comment by ThomasBurleson** [comment]
@aminx4 - try `npm install protractor -g` then `webdriver-manager update`.

**Comment by aminx4** [comment]
This is the stack that i had when i tape npm install protractor -g




D:\Formations\Angular Material Design\Repository\material-start>npm install prot
ractor -g
-


> utf-8-validate@1.1.0 install C:\Users\amine.chikouche\AppData\Roaming\npm\node
_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules
\utf-8-validate
> node-gyp rebuild


C:\Users\amine.chikouche\AppData\Roaming\npm\node_modules\protractor\node_module
s\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate>if not defined
npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp
-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_m
ain.py", line 11, in <module>
    import gyp
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\__init__.py", line 8, in <module>
    import gyp.input
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\input.py", line 873
    except ImportError as e:
                        ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\amine.chikouche\AppData\Roaming\npm\node_modules\protracto
r\node_modules\selenium-webdriver\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

> bufferutil@1.1.0 install C:\Users\amine.chikouche\AppData\Roaming\npm\node_mod
ules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\buf
ferutil
> node-gyp rebuild


C:\Users\amine.chikouche\AppData\Roaming\npm\node_modules\protractor\node_module
s\selenium-webdriver\node_modules\ws\node_modules\bufferutil>if not defined npm_
config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin
\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_m
ain.py", line 11, in <module>
    import gyp
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\__init__.py", line 8, in <module>
    import gyp.input
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\input.py", line 873
    except ImportError as e:
                        ^
SyntaxError: invalid syntax
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\amine.chikouche\AppData\Roaming\npm\node_modules\protracto
r\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
C:\Users\amine.chikouche\AppData\Roaming\npm\protractor -> C:\Users\amine.chikou
che\AppData\Roaming\npm\node_modules\protractor\bin\protractor
C:\Users\amine.chikouche\AppData\Roaming\npm\webdriver-manager -> C:\Users\amine
.chikouche\AppData\Roaming\npm\node_modules\protractor\bin\webdriver-manager
protractor@2.1.0 C:\Users\amine.chikouche\AppData\Roaming\npm\node_modules\protr
actor
├── jasminewd@1.1.0
├── jasminewd2@0.0.5
├── html-entities@1.1.2
├── saucelabs@0.1.1
├── q@1.0.0
├── minijasminenode@1.1.1
├── adm-zip@0.4.4
├── lodash@2.4.2
├── accessibility-developer-tools@2.6.0
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── jasmine@2.3.1 (exit@0.1.2, jasmine-core@2.3.4)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── source-map-support@0.2.10 (source-map@0.1.32)
├── request@2.36.0 (aws-sign2@0.5.0, qs@0.6.6, forever-agent@0.5.2, oauth-sign@0
.3.0, tunnel-agent@0.4.0, json-stringify-safe@5.0.1, mime@1.2.11, node-uuid@1.4.
3, tough-cookie@1.1.0, http-signature@0.10.1, hawk@1.0.0, form-data@0.1.4)
└── selenium-webdriver@2.45.1 (tmp@0.0.24, xml2js@0.4.4, rimraf@2.3.4, ws@0.7.2)

**Comment by aminx4** [comment]
This is the stack that i had when i tape 

        npm install protractor -g

![stack1](https://cloud.githubusercontent.com/assets/1623716/7774094/10e6dcbe-00a9-11e5-9010-cf683bdcc8ee.png)
![stack2](https://cloud.githubusercontent.com/assets/1623716/7774124/3d6563a0-00a9-11e5-968d-a6e2436f6f8b.png)

**Comment by ceoaliongroo** [comment]
Try update the packages outdated first:
```bash
npm outdated -g
````
Check that outdated in the list will be update:
```bash
npm update -g
```

After is the error persist, you could check if all the prerequisite are installed
https://github.com/TooTallNate/node-gyp#installation

**Comment by ThomasBurleson** [comment]
For better support/responses, this best posted in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by mprentic-harris** [comment]
@aminx4 Did you get this resolved? On Windows, we've had to install the Windows 7 SDK and Visual Studio Express in order to get Protractor to build due to its dependency on one of the SASS plugins. The link posted by @ceoaliongroo has more details about this.
