### ISSUE TITLE
Unit testing angular-material code with JSPM

### ISSUE THREAD

**Issue by jannisg** [angular/material-start#41]
As a follow on from the discussion on https://github.com/angular/material/issues/2971 I would appreciate any help and guidance you can provide with setting up JSPM using `angular-material-mocks.js` to unit test code that makes use of `$mdDialog` for example.

My initial hurdle is that after `jspm install angular-material` I do have the `src/jspm_packages/github/angular/bower-material@0.9.4/angular-material-mocks.js` file but `import 'angular-material-mocks';` for example wouldn't work as there is no path configured for that specific file.

Ideally I would be able to write such an import statement so that our unit tests (or karma config file) don't reference a specific version string, e.g. `0.9.4` in the path to the file.

Any help would be much appreciated.

**Comment by robcleghorn** [comment]
Any updates on when this issue may be solved?

**Comment by vanslly** [comment]
I have gotten the following working for using `angular-material-mocks`:

```JavaScript
'use strict';

import 'angular';
import 'angular-mocks';
import 'angular-material/angular-material-mocks'; // import ngMaterial-mock
import errorDialogModule from './error-dialog.module';

describe('error-dialog.directive', () => {
    let _errorDialog,
        _$mdDialog;

    beforeEach(() => {
        angular.mock.module('ngMaterial-mock'); // use ngMaterial-mock
        angular.mock.module(errorDialogModule.name);

        inject((errorDialog, $mdDialog) => {
            _errorDialog = errorDialog;
            _$mdDialog = $mdDialog;
        });
    });

    describe('show()', () => {

        it ('should delegate opening to the material dialog', () => {
            spyOn(_$mdDialog, 'show').and.callThrough();
            
            let options = {};
            _errorDialog.show(options);
            
            expect(_$mdDialog.show).toHaveBeenCalledWith(options);
        });

    });
});
```

Looking into `angular-material-mocks` however it doesn't mock `$mdDialog` so to mock `$mdDialog`:

```JavaScript
'use strict';

import 'angular';
import 'angular-mocks';
import errorDialogModule from './error-dialog.module';

describe('error-dialog.directive', () => {
    let _errorDialog,
        _$mdDialogMock;

    beforeEach(() => {
        angular.mock.module(errorDialogModule.name);
        
        // override $mdDialog with mock
        angular.mock.module($provide => {
            $provide.value('$mdDialog', {
                show: jasmine.createSpy('show')
            });
        });

        inject((errorDialog, $mdDialog) => {
            _errorDialog = errorDialog;
            _$mdDialogMock = $mdDialog;
        });
    });

    describe('show()', () => {

        it ('should delegate opening to the material dialog', () => {
            let options = {};
            _errorDialog.show(options);
            expect(_$mdDialogMock.show).toHaveBeenCalledWith(options);
        });

    });
});
```

It seems that if mocking the material components, then `ngMaterial-mock` is not required, it seems best suited when calling through to material.

**Comment by ThomasBurleson** [comment]
@vanslly - Can you publish your jsmp config and the karma  settings? That would be very helpful to all.

**Comment by topherfangio** [comment]
Since this issue has seen no movement, I am going to go ahead and close it. Please reach out if you're still having issues and we will reopen and attempt to assist.
