### ISSUE TITLE
Problem with README.md

### ISSUE THREAD

**Issue by chinnichaitanya** [angular/material-start#42]
In the README.md, [here](https://github.com/angular/material-start/blame/master/README.md#L202), it says ```sudo npm install -g live-server```

But according to [this](http://stackoverflow.com/a/4999441/3476748) and [this](http://hood.ie/blog/why-you-shouldnt-use-sudo-with-npm.html), using ```sudo``` with ```npm``` is not recommended.

So it would be better to change it to ```npm install -g live-server```

**Comment by ThomasBurleson** [comment]
agreed.

**Comment by ThomasBurleson** [comment]
Fixed.
