### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by babakness** [angular/material-start#44]
> node-gyp rebuild

  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:343:5: error: no member named 'ThrowException' in
      namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../node_modules/nan/nan.h:343:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


[snip]

fails.

**Comment by mprentic-harris** [comment]
What platform are you on? What version of node.js and npm are installed? Do you have all of the requirements listed here? https://github.com/TooTallNate/node-gyp#installation

**Comment by evan10s** [comment]
Just a note - I was getting a lot of install errors because I didn't know I didn't have all the prerequisite software installed.  If you're having trouble, make sure you have everything at the @mprentic-harris provided above.

**Comment by apinnecke** [comment]
Same here @ Node v0.12.5 & OSX 10.10

http://pastebin.com/3P5fb4eP

**Comment by jonigl** [comment]
I have exactly the same @mprentic-harris 's issue. I have OS X 10.11.1 and I have npm version 3.3.12 node version v5.4.1 and I have all the prerequisite commented by @mprentic-harris

I've tried almost everything... Please help...

**Comment by jonigl** [comment]
Thanks @ThomasBurleson ! this solve the problem.

**Comment by ThomasBurleson** [comment]
:+1:
