### ISSUE TITLE
icon become square

### ISSUE THREAD

**Issue by fxp** [angular/material-start#45]
After add three users in UserService the avatars become square shape instead of round

**Comment by badoet** [comment]
it happened to me too once. but turned out its my css is overriding the style. 
becareful of css loading sequence.

**Comment by fxp** [comment]
@badoet it can be reproduce everytime. just clone the repo, add two more user info in UserService.js.

**Comment by petealbertson** [comment]
It also happens to me whenever I open the inspector in Chrome.

**Comment by andrewmcconville** [comment]
It happens to me when <md-sidenav> has a scrollbar. This might be what is happening to @fxp when he adds more than three users, his height becomes tall enough to require the md-sidenav to scroll. This might also be what is happening to @petealbertson when opening the inspector, the viewport is short with the inspector open that a scroll bar is needed in the md-sidenav.

When I drag my viewport taller and the scroll bar on the md-sidenav goes away the .avatar's go round. When I drag the viewport shorter the .avatar's go square. You can drag the viewport back and forth and they change instantly.

It also looks like the .avatar is actually staying round, but it's the SVG's that are popping out, even though the .avatar is set to overflow: hidden. Somehow the SVG's are not respecting the overflow when a scroll bar is present on the md-sidenav.
