### ISSUE TITLE
Layout markup does not match the wireframe

### ISSUE THREAD

**Issue by cquillen2003** [angular/material-start#47]
I am trying to follow the ES5 tutorial and I am confused with Step #3.

On Step #2 the markup clearly matches the wireframe: the first child element of the body tag is md-toolbar.  On Step #3, the first child element of the body tag is md-sidenav.  Why the change?

By Step #6 it's back to matching the wireframe.  However, the clone of the material-start repository that I have as my starter project (SHA 2de1e8c) also does not match the wireframe and has md-sidenav as the first child element of the body.  Am I missing something?

Thanks!

**Comment by ThomasBurleson** [comment]
This Layout markup is deliberately different to show how the SideNav can have a header and overlay the content area (in small window sizes).  This is deliberately done to demonstrate two (2) different layouts possibilities.
