### ISSUE TITLE
Confusing instructions in README.md

### ISSUE THREAD

**Issue by evan10s** [angular/material-start#48]
The instructions in the Run End-to-End Tests section of the readme are confusing.  I was confused because I was trying to run the `live-server` command before I had installed `live-server`, as it seems from the beginning Getting Started section that there are going to be more step-by-step instructions.

In the Getting Started section, in the Run End-to-End Tests section, I think there needs to be a note that you have to first install `live-server`; that was not clear and led to much confusion for me because at first, I did not understand what was happening.

**Comment by fredericksilva** [comment]
[running-the-app-during-development](https://github.com/angular/material-start#running-the-app-during-development) contains instructions to install live-server

**Comment by rsparrow** [comment]
Note: I agree with evan10s. Because "running-the-app-during-development" is later in the doc I found myself googling and found this open issue.

**Comment by johanbove** [comment]
:+1:  for moving the "install live-server" step upwards in the documentation. Had the same issue as @rsparrow

**Comment by ThomasBurleson** [comment]
Fixed with SHA 8c593c7f3
