### ISSUE TITLE
An "es6-tutorial" branch needs to be created.

### ISSUE THREAD

**Issue by john-jay** [angular/material-start#57]
The files tutorial_0.html, etc., are not available for es6.

**Comment by luck02** [comment]
The instructions in the es-6 branch are pretty confusing, there's no actual tutorials (That I can find) in the es-6 branch.  However the readme states there should be.

**Comment by gfviegas** [comment]
At least need to remove the link to a non existing branch. Get a (on development) message or something. Really confusing

**Comment by ThomasBurleson** [comment]
Fixed - https://github.com/angular/material-start/blob/es6/README.md

**Comment by luck02** [comment]
The README in the master branch still has a link to es6 tutorial branch. 
```
Branch Starter - ES6 Tutorials: for ES6 Tutorial steps & development process.
```

It would be good to fix that and put a note as to whether tehre's any intention towards producing an es6 tutorial branch.

Thank you.

**Comment by ThomasBurleson** [comment]
Done - https://github.com/angular/material-start/blob/master/README.md

**Comment by luck02** [comment]
Awesome, thank you
