### ISSUE TITLE
Sidenav items don't deactivate on mouse leave

### ISSUE THREAD

**Issue by alexmick** [angular/material-start#66]
If the user clicks an item in the sidenav but drags his mouse out before relasing the click, the ripple effect will stay completely on indefinitely like so :

<img width="573" alt="screen shot 2015-11-05 at 12 29 07" src="https://cloud.githubusercontent.com/assets/926312/10967183/f89e8c68-83b8-11e5-9c4f-1865b2a5be98.png">

This happened to me while attempting to scroll the list.

**Comment by ThomasBurleson** [comment]
This is a known issue with Ripples in Angular Material; improvements to Ripple are in-progress.

**Comment by ThomasBurleson** [comment]
Fixed.
