### ISSUE TITLE
I tried to start using angular material but encountered the following error: Uncaught Error: [$injector:nomod] Module 'material.components.menuBar' is not available!

### ISSUE THREAD

**Issue by aliyuaminu** [angular/material-start#72]
Uncaught Error: [$injector:nomod] Module 'material.components.menuBar' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by aliyuaminu** [comment]
Any help I'm grateful.

**Comment by ThomasBurleson** [comment]
Please post this in the [Angular Material Forum](https://groups.google.com/forum/#!forum/ngmaterial)

**Comment by Snehal1112** [comment]
@aliyuaminu  can i see your code ?

**Comment by aliyuaminu** [comment]
It is not a my code @Snehal1112 , I build a documentation for angularJS Material design, I tried to run it in my localhost server, but I keep getting that error, rather.

**Comment by aliyuaminu** [comment]
I tried http://ui.lumapps.com/ too, still the same error.
