### ISSUE TITLE
Change urls from absolute paths to relative

### ISSUE THREAD

**Issue by kmturley** [angular/material-start#74]
When running the angular-start app locally it is expecting a server run at the root e.g:

    http://localhost:8888/

However when running as another url the app urls don't always work e.g.

    http://localhost:8888/material-start/app/

The solution to this is to change url paths from absolute to relative:

    templateUrl: '/src/users/view/contactSheet.html',

should become:

    templateUrl: './src/users/view/contactSheet.html',

Then it works!

**Comment by ThomasBurleson** [comment]
Fixed.
