### ISSUE TITLE
Why do you still use bower when you bet on jspm

### ISSUE THREAD

**Issue by HansS** [angular/material-start#76]
jspm can do all the stuff! 
Bower is getting old!

**Comment by ThomasBurleson** [comment]
Please note that this repository has 3 main branches: 

* master (es5)
* es5-tutorial
* es6

Only the **es6** branch uses `jspm`, the others use `bower` for **es5** efforts. 

![screen shot 2015-12-14 at 5 34 49 am](https://cloud.githubusercontent.com/assets/210413/11780021/6d607ece-a224-11e5-97c2-a552c2b44b4d.png)
