### ISSUE TITLE
Tutorial Feedback

### ISSUE THREAD

**Issue by Mazus** [angular/material-start#78]
Hello,
Thanks for this tutorial. I would like to help improving it by giving some feedbacks, if that's not the right place please tell me:
1 - Not a git expert (yet) but for the Step-by-step tutorial (#0 through #8) it would be nice to give the command to clone just the branch, and not the master : <code>git clone -b es5-tutorial --single-branch https://....</code>.
2 - step 3 description is the same as step 2 description
3 - JSDoc for UserController, selectUser are incorrect (wrong params or missing params)
4 - In tutorial_5.html, the icon registering is not highlighted, nor the declaration of UserController as ul and the adding menu icon in the toolbar. (might be intented)
5 - By the way, wouldn't it be clearer to call UserController "uc" insteadd of ul (why ul ?), and users elements "user" instead of it (like iteration ?)
6 - You switch between ng-svg-src and ng-svg-icon without telling why, and in this case it makes no difference.
7 -  In tutorial_6.html, the icon registering is not highlighted, nor hiding the menu icon when displayed or the click support  (might be intented)
8- 

A last point which is not directly related to this tutorial but more to the angular-seed project :
For new comers, it's really overwhelming to see all thoses node_modules install, considering those are mainly intented for testing purpose. Beginners need to see each new point step by step, so it seems unnecessary to run "npm install" (which downloads like 1 billion files), when all you need to do this tutorial is "bower install".
Maybe you should come to this point when we get to the e2e testing part, so that it's really clear why all those modules are for.

Thanks again for this tutorial.

**Comment by ThomasBurleson** [comment]
Within 1-2 weeks, we will have a full video set "Introduction to Angular Material" on Egghead.io. Those videos will be using the ES5 tutorials and provide some details. I will also be presenting an ES6 tutorial set at the **ng-nl** conference in February; that recording should be on YouTube before the end of February.

**Comment by Mazus** [comment]
Cool, eager to see that.
