### ISSUE TITLE
`$mdMedia` used directly inside the template?

### ISSUE THREAD

**Issue by dmitriz** [angular/material-start#83]
I'm puzzled by the usage of `md-is-locked-open="$mdMedia('gt-sm')"` inside the template:
https://github.com/angular/material-start/blob/master/app/index.html#L30

I have never seen this use.

Is this intended use?
How is `$mdMedia` injected?

**Comment by ajoslin** [comment]
It's Magic :tm: 

https://github.com/angular/material/blob/master/src/components/sidenav/sidenav.js#L233-L242

**Comment by dmitriz** [comment]
Actually it is documented:

https://github.com/angular/material/blob/master/src/components/sidenav/sidenav.js#L203

**Comment by ThomasBurleson** [comment]
```js
var isLockedOpenParsed = $parse(attr.mdIsLockedOpen);
    var isLocked = function() {
      return isLockedOpenParsed(scope.$parent, {
        $media: function(arg) {
          $log.warn("$media is deprecated for is-locked-open. Use $mdMedia instead.");
          return $mdMedia(arg);
        },
        $mdMedia: $mdMedia
      });
    };
```

`$parse( ... )` returns a `function(contextScope, locals)` that allows **locals** to be injected into the context scope.
