### ISSUE TITLE
How to start the exmples?

### ISSUE THREAD

**Issue by FabioParigi** [angular/material-start#88]
I'm a material beginner, I download the project 
execute:
npm install
bower install angular-material -D

but after, how to launch node, there isn't any app.js???
please help me how to lounch the examples

thanks
Fabio

**Comment by traqutor** [comment]
Fabio you already install only dependency module with bower the app is what you as a programmer should do :-)
may be this help
https://github.com/angular/material-start/tree/es6

**Comment by FabioParigi** [comment]
@traqutor 
thanks for your fast reply.... 
I install all but how I can start the index.html file and the tutorial on my browser.
How I can show my index.html for example on http://localhost:8080

In all of my project I lounc a js file with node (ex. node app.js) the webserver start and I can see my file.
But here theres nothing?
can you help me?
thanks

**Comment by FabioParigi** [comment]
ok found the solution
https://github.com/angular/material-start/tree/es5

**Comment by ThomasBurleson** [comment]
@FabioParigi - please see the [ES5 Tutorials and README](https://github.com/angular/material-start/tree/es5-tutorial)
