### ISSUE TITLE
Tutorial instructions are incorrect

### ISSUE THREAD

**Issue by bsilvers** [angular/material-start#92]
1. Cloning material-start as instructed does not give you the files that are described in the tutorial. It only gives you the finished product. 
2. Trying to circumvent issue #1 by downloading the zip file produces files with missing links and file names that do not match the tutorial.
3. The tutorial code instructions do not match the JS Bin code links that have the working steps

**Comment by ThomasBurleson** [comment]
The `master` [README](https://github.com/angular/material-start) states 

*  Branch master: contains the finished, ES5, material-starter application.
*  Branch Starter - ES5 Tutorials: contains the ES5 tutorials with development Lession #1 - #7.
